config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  resources :mixes, :path => 'collection' do
    resources :songs, :path => 'mixtape'
  end


  authenticated :user do
    root to: 'mixes#index', as: :authenticated_root
  end
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mix.rb
class Mix < ApplicationRecord
  has_many :songs
  belongs_to :user
  accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :mix
  belongs_to :user

  def parse_video_url(url)
    @url = url

    youtube_formats = [
        %r(https?://youtu\.be/(.+)),
        %r(https?://www\.youtube\.com/watch\?v=(.*?)(&|#|$)),
        %r(https?://www\.youtube\.com/embed/(.*?)(\?|$)),
        %r(https?://www\.youtube\.com/v/(.*?)(#|\?|$)),
        %r(https?://www\.youtube\.com/user/.*?#\w/\w/\w/\w/(.+)\b)
      ]

    @url.strip!

    if @url.include? "youtu"
      youtube_formats.find { |format| @url =~ format } and $1
      @results = $1
      @results
    else
      return nil # There should probably be some error message here
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :mixes
  has_many :songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController
  before_action :set_mix, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /mixes
  # GET /mixes.json
  def index
    @mixes = current_user.mixes
  end

  def show
    @songs = @mix.songs
    @song = @mix.songs.build
    @mix = Mix.find(params[:id])
  end

  # GET /mixes/new
  def new
    @mix = current_user.mixes.build
  end

  # GET /mixes/1/edit
  def edit
  end

  # POST /mixes
  # POST /mixes.json
  def create
    @mix = current_user.mixes.build(mix_params)

    respond_to do |format|
      if @mix.save
        format.html { redirect_to mix_songs_url(@mix), notice: 'Mix was successfully created.' }
        format.json { render :show, status: :created, location: @mix }
      else
        format.html { render :new }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mixes/1
  # PATCH/PUT /mixes/1.json
  def update
    respond_to do |format|
      if @mix.update(mix_params)
        format.html { redirect_to mixes_path(@mix), notice: 'Mix was successfully updated.' }
        format.json { render :show, status: :ok, location: @mix }
      else
        format.html { render :edit }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mixes/1
  # DELETE /mixes/1.json
  def destroy
    @mix.destroy
    respond_to do |format|
      format.html { redirect_to mixes_url, notice: 'Mix was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mix
      @mix = Mix.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mix_params
      params.require(:mix).permit(:title, :description, songs_attributes: [:id, :artist, :title, :link, :_destroy])
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_songs
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET mixes/1/songs
  def index
    @songs = @mix.songs
    @song = @mix.songs.build
    @mix = Mix.find(params[:mix_id])
  end

  # GET mixes/1/songs/1
  # def show
  # end

  # GET mixes/1/songs/new
  def new
    @song = @mix.songs.build
  end

  # GET mixes/1/songs/1/edit
  # def edit
  # end

  # POST mixes/1/songs
  def create
    @song = @mix.songs.build(song_params)
    @song.link = @song.parse_video_url(@song.link)

    if @song.save
      redirect_to(mix_path(@mix), notice: 'Song was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT mixes/1/songs/1
  def update
    if @song.update_attributes(song_params)
      redirect_to([@song.mix, @song], notice: 'Song was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE mixes/1/songs/1
  def destroy
    @song.destroy

    redirect_to mix_songs_url(@mix)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_songs
      @mix = Mix.find(params[:mix_id])
    end

    def set_song
      @song = @mix.songs.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def song_params
      params.require(:song).permit(:artist, :title, :link).merge(user_id: current_user.id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mixes_helper.rb
module MixesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mixed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <% if user_signed_in? %>
    <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
    <% elsif !user_signed_in? %>
    <%= link_to 'Sign Up', new_user_registration_path %>
    <%= link_to 'Log In', new_user_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/mixes/_addsong.html.erb
<%= form_for([@song.mix, @song]) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit "Add song to mix" %>
  </div>
<% end %>

app/views/mixes/_form.html.erb
<%= form_for(@mix) do |f| %>
  <% if @mix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mix.errors.count, "error") %> prohibited this mix from being saved:</h2>

      <ul>
      <% @mix.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mixes/edit.html.erb
<h1>Editing Mix</h1>

<%= render 'form', mix: @mix %>

<%= link_to 'Show', @mix %> |
<%= link_to 'Back', mixes_path %>

app/views/mixes/index.html.erb
<h1>My Mixtapes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mixes.each do |mix| %>
      <tr>
        <td><%= mix.title %></td>
        <td><%= mix.description %></td>
        <td><%= link_to 'Show Mix', mix_path(mix) %></td>
        <% if mix.user == current_user %>
        <td><%= link_to 'Change Name', edit_mix_path(mix) %></td>
        <td><%= link_to 'Delete', mix, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mix', new_mix_path %>

app/views/mixes/new.html.erb
<h1>New Mix</h1>

<%= render 'form', mix: @mix %>

<%= link_to 'Back', mixes_path %>

app/views/mixes/show.html.erb
<% if user_signed_in? %>
<%= link_to 'My Mixes', mixes_path %>
<% end %>

<br>
<br>
<h1><%= @mix.title %></h1>
<p><%= @mix.description %></p>
<div id="share"></div>
<br>
<% if @mix.user == current_user %>
<h3>Add a song</h3>
<%= render 'addsong' %>
<% end %>
<br>
<table>
  <tr>
    <th>Artist</th>
    <th>Title</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.reverse.drop(1).reverse.each do |song| %>
  <tr>
    <td><%= song.artist %></td>
    <td><%= song.title %></td>
    <td><%= song.link %></td>
    <td class="song" data-video-id="<%= song.link %>">Launch</td>
    <td class="play">Play</td>
    <td class="pause">Pause</td>
    <% if song.user == current_user %>
      <% if (1 > 2) %>
        <td><%= link_to 'Edit', edit_mix_song_path(song.mix, song) %></td>
      <% end %>
    <td style="color:red;text-decoration:none;"><%= link_to 'Delete', [song.mix, song], :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>
<div id="video-placeholder"></div>

<script src="https://www.youtube.com/iframe_api"></script>
<script>
  var player;
  function onYouTubeIframeAPIReady() {
      player = new YT.Player('video-placeholder', {
          width: 320,
          height: 200,
          videoId: '',
          playerVars: {
              color: 'white',
              playlist: ''
          },
          events: {
              onReady: initialize
          }
      });
  }
  function initialize(){
  }
  $('.play').on('click', function () {
      player.playVideo();
  });
  $('.pause').on('click', function () {
      player.pauseVideo();
  });
  $('.song').on('click', function () {
      var url = $(this).attr('data-video-id');
      player.cueVideoById(url);
      $('#video-placeholder').css('display', 'block')
      player.playVideo();
  });
</script>
<script>
    $("#share").jsSocials({
      showLabel: false,
      showCount: false,
        shares: ["email", "twitter", "facebook", "googleplus", "linkedin", "pinterest", "stumbleupon", "whatsapp"]
    });

</script>

app/views/songs/_form.html.erb
<%= form_for([@song.mix, @song]) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit "Add song to mix" %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', [@song.mix, @song] %> |
<%= link_to 'Back', mix_songs_path(@song.mix) %>

app/views/songs/index.html.erb
<% if user_signed_in? %>
<%= link_to 'My Mixes', mixes_path %>
<% end %>

<br>
<br>
<h1><%= @mix.title %></h1>
<p><%= @mix.description %></p>
<div id="share"></div>
<br>
<% if @mix.user == current_user %>
<h3>Add a song</h3>
<%= render 'form' %>
<% end %>
<br>
<table>
  <tr>
    <th>Artist</th>
    <th>Title</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.reverse.drop(1).reverse.each do |song| %>
  <tr>
    <td><%= song.artist %></td>
    <td><%= song.title %></td>
    <td><%= song.link %></td>
    <td class="song" data-video-id="<%= song.link %>">Launch</td>
    <td class="play">Play</td>
    <td class="pause">Pause</td>
    <% if song.user == current_user %>
      <% if (1 > 2) %>
        <td><%= link_to 'Edit', edit_mix_song_path(song.mix, song) %></td>
      <% end %>
    <td style="color:red;text-decoration:none;"><%= link_to 'Delete', [song.mix, song], :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>
<div id="video-placeholder"></div>

<script src="https://www.youtube.com/iframe_api"></script>
<script>
  var player;
  function onYouTubeIframeAPIReady() {
      player = new YT.Player('video-placeholder', {
          width: 320,
          height: 200,
          videoId: '',
          playerVars: {
              color: 'white',
              playlist: ''
          },
          events: {
              onReady: initialize
          }
      });
  }
  function initialize(){
  }
  $('.play').on('click', function () {
      player.playVideo();
  });
  $('.pause').on('click', function () {
      player.pauseVideo();
  });
  $('.song').on('click', function () {
      var url = $(this).attr('data-video-id');
      player.cueVideoById(url);
      $('#video-placeholder').css('display', 'block')
      player.playVideo();
  });
</script>
<script>
    $("#share").jsSocials({
      showLabel: false,
      showCount: false,
        shares: ["email", "twitter", "facebook", "googleplus", "linkedin", "pinterest", "stumbleupon", "whatsapp"]
    });

</script>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', mix_songs_path(@song.mix) %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Artist:</b>
  <%= @song.artist %>
</p>

<p>
  <b>Title:</b>
  <%= @song.title %>
</p>

<p>
  <b>Link:</b>
  <%= @song.link %>
</p>


<%= link_to 'Edit', edit_mix_song_path(@song.mix, @song) %> |
<%= link_to 'Back', mix_songs_path(@song.mix) %>

app/views/welcome/index.html.erb
<div class="stars">
</div>
<h2 class="logo">Mixed</h2>

<link href='https://fonts.googleapis.com/css?family=Lato:900,400|Shadows+Into+Light' rel='stylesheet' type='text/css'>

<link href='https://fonts.googleapis.com/css?family=Lato:900,400|Shadows+Into+Light' rel='stylesheet' type='text/css'>